[package]
name = "aldous-broder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maze-grid = { version = "0.1.0", path = "../maze-grid" }
rand = "0.8.5"
